### ISSUE TITLE
Compile fails when modifying $theme-body-background-color

### ISSUE THREAD

**Issue by Morsey187** [uswds/uswds#4643]
### Describe the bug
Setting a custom `$theme-body-background-color` value to anything other then "white" will throw an error:
```
error - ./stylesheets/index.scss:86:0
Module not found: Can't resolve 'uswds/dist/img/usa-icons-bg/arrow_back--white.svg'

Import trace for requested module:
./stylesheets/index.scss
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
```

### Steps to reproduce the bug
1. Modify the value for `$theme-body-background-color` and compile.

### System setup
- **USWDS version:** 2.11.2
- **Device:** Macbook pro 12-inch, 2019
- **Operating system:** macOS Monterey 12.2.1 running Node 16 using NVM.

### Additional context
I believe this error is likely related to the `add-color-icon` mixin and specifically the `$icon-breadcrumb-separator` and `$icon-breadcrumb-back` variables, as manually adding files `arrow_back--white.svg` and `navigate_next--white.svg` to the `usa-icons-bg` directory works as a temporary fix.
I've setup my build using NextJs and react-uswds as part of a private git repoistory, however I can enquire about sharing the code from the repository if this issue can't be replicated on other peoples builds and looks to be more invovled than missing assets.

**Comment by brunerae** [comment]
Thanks for flagging @Morsey187 ! We'll look into it.

**Comment by amyleadem** [comment]
Confirming that this error occurs in 3.0.1 during storybook start/build
Full error details: 
```
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../uswds-core/src/styles/mixins/img/usa-icons-bg/arrow_back--white.svg' in '/Users/aleadem/Dev/github/uswds/packages/uswds'
    at finishWithoutResolve (/Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/Resolver.js:309:18)
    at /Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at /Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/AliasPlugin.js:125:14
    at next (/Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/forEachBail.js:14:3)
    at forEachBail (/Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/forEachBail.js:24:9)
    at /Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/lib/AliasPlugin.js:51:5
    at _next0 (eval at create (/Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/aleadem/Dev/github/uswds/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at processResult (/Users/aleadem/Dev/github/uswds/node_modules/webpack/lib/NormalModule.js:743:19)
    at /Users/aleadem/Dev/github/uswds/node_modules/webpack/lib/NormalModule.js:844:5
    at /Users/aleadem/Dev/github/uswds/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Users/aleadem/Dev/github/uswds/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/Users/aleadem/Dev/github/uswds/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/aleadem/Dev/github/uswds/node_modules/css-loader/dist/index.js:155:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```
